apiVersion: v1
kind: Namespace
metadata:
  name: spicedb-custom-registry
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: example-with-custom-registry
  namespace: spicedb-custom-registry
spec:
  # Use an alternative container registry
  # The operator will append the appropriate tag based on version/channel
  # NOTE: Do NOT include a tag here - just the registry and image name
  baseImage: "my-registry.company.com/authzed/spicedb"
  
  # Specify the version to use
  version: "v1.33.0"
  
  # Alternatively, use a channel for automatic updates within that channel
  # channel: "stable"
  
  config:
    datastoreEngine: postgres
    logLevel: info
    
  secretName: spicedb-config
  
  # If using a private registry, use patches to add imagePullSecrets to the deployment
  patches:
    - kind: Deployment
      patch: |
        spec:
          template:
            spec:
              imagePullSecrets:
                - name: registry-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
  namespace: spicedb-custom-registry
stringData:
  datastore_uri: "postgresql://<CHANGE-ME-USERNAME>:<CHANGE-ME-PASSWORD>@<CHANGE-ME-POSTGRES-HOST>:5432/<CHANGE-ME-DATABASE>?sslmode=require"
  preshared_key: "<CHANGE-ME-TO-A-VERY-SECRET-PRESHARED-KEY>"
---
# If using a private registry, you may need an image pull secret
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: spicedb-custom-registry
type: kubernetes.io/dockerconfigjson
data:
  # CHANGE-ME: This is a placeholder - replace with your actual registry credentials
  # Generate with: kubectl create secret docker-registry registry-credentials --docker-server=my-registry.company.com --docker-username=YOUR-USERNAME --docker-password=YOUR-PASSWORD --dry-run=client -o yaml
  .dockerconfigjson: <CHANGE-ME-BASE64-ENCODED-DOCKER-CONFIG>
