# vim: syntax=dockerfile
FROM gcr.io/distroless/base
COPY validated-update-graph.yaml /opt/operator/config.yaml
COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.18 /ko-app/grpc-health-probe /usr/local/bin/grpc_health_probe
COPY spicedb-operator /usr/local/bin/spicedb-operator
ENTRYPOINT ["spicedb-operator"]
