apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:16.6-alpine3.21
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init
          configMap:
            name: init
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-public
  labels:
    app: postgresql-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql-db
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: init
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = 500;"
