apiVersion: v1
kind: Namespace
metadata:
  name: spicedb-separate-migration
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: example-separate-migration
  namespace: spicedb-separate-migration
spec:
  # Number of SpiceDB replicas
  replicas: 3
  
  config:
    datastoreEngine: postgres
    logLevel: info
    
  secretName: spicedb-config
---
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
  namespace: spicedb-separate-migration
stringData:
  # Application datastore URI - used by SpiceDB pods
  # This user should have limited privileges (SELECT, INSERT, UPDATE, DELETE)
  datastore_uri: "postgresql://CHANGE-ME-APP-USER:CHANGE-ME-APP-PASSWORD@CHANGE-ME-POSTGRES-HOST:5432/CHANGE-ME-DATABASE?sslmode=require"
  
  # Migration datastore URI - used only by migration jobs
  # This user needs elevated privileges (CREATE, DROP, ALTER tables)
  migration_datastore_uri: "postgresql://CHANGE-ME-ADMIN-USER:CHANGE-ME-ADMIN-PASSWORD@CHANGE-ME-POSTGRES-HOST:5432/CHANGE-ME-DATABASE?sslmode=require"
  
  # Shared preshared key for API authentication
  preshared_key: "CHANGE-ME-TO-A-VERY-SECRET-PRESHARED-KEY"