apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: spicedb-operator
  name: spicedb-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spicedb-operator
    app.kubernetes.io/instance: spicedb-operator
  name: spicedb-operator
  namespace: spicedb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spicedb-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spicedb-operator
        app.kubernetes.io/instance: spicedb-operator
    spec:
      containers:
        - args:
          - run
          - -v=4
          - --crd=false
          - --config
          - /opt/operator/config.yaml
          image: quay.io/cloudservices/kessel-spicedb-operator:c85ae2c
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          name: spicedb-operator
          ports:
            - containerPort: 8080
              name: prometheus
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
            requests:
              cpu: "20m"
              memory: "32Mi"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: spicedb-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spicedb-operator
  namespace: spicedb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spicedb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spicedb-operator
subjects:
  - kind: ServiceAccount
    name: spicedb-operator
    namespace: spicedb-operator
