---
name: "CLA"
on:  # yamllint disable-line rule:truthy
  issue_comment:
    types:
      - "created"
  pull_request_target:
    types:
      - "opened"
      - "closed"
      - "synchronize"
jobs:
  cla:
    name: "Check Signature"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "authzed/actions/cla-check@main"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          cla_assistant_token: "${{ secrets.CLA_ASSISTANT_ACCESS_TOKEN }}"
